CREATE DATABASE MTM;
GO

USE MTM;

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TaxScheduleTypes](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UC_Name] UNIQUE NONCLUSTERED 
(
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MunicipalityTaxSchedules](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TaxSheduleTypeID] [int] NOT NULL,
	[MunicipalityName] [nvarchar](200) NOT NULL,
	[FromDate] [date] NOT NULL,
	[TODate] [date] NULL,
	[TaxAmount] DECIMAL(5,2) NOT NULL,
	[CreatedOn] [datetime] NOT NULL,
	[ModifiedOn] [datetime] NULL,
	CHECK (TaxAmount>0),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UC_TaxSheduleTypeID_MunicipalityName_FromDate_TODate] UNIQUE NONCLUSTERED 
(
	[TaxSheduleTypeID] ASC,
	[MunicipalityName] ASC,
	[FromDate] ASC,
	[TODate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MunicipalityTaxSchedules]  WITH CHECK ADD FOREIGN KEY([TaxSheduleTypeID])
REFERENCES [dbo].[TaxScheduleTypes] ([ID])
GO


